---
name: Pull x86 Image and Sync to ACR
on:
  workflow_dispatch: null
jobs:
  sync-image:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取x86架构的nginx镜像
        run: >
          docker pull --platform linux/amd64 nginx:1.20.2

          docker tag nginx:1.20.2 ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/nginx:x86-1.20.2
      - name: 登录阿里云ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: 推送镜像到ACR
        run: >
          docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE
          }}/nginx:x86-1.20.2
